### ISSUE TITLE
Feature: User can add a class

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a course 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will add course to the page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/46547520/209753018-c033c17c-a621-4ce6-a227-f27f2d03c53f.png)
![image](https://user-images.githubusercontent.com/46547520/209753130-f204dbc4-d946-4364-be7f-ab2d57944b62.png)
![image](https://user-images.githubusercontent.com/46547520/209753190-e57eb9e3-1305-4fc6-91cb-e12ffd5937f9.png)
![image](https://user-images.githubusercontent.com/46547520/209753266-c979feb1-9ec8-413f-b643-bcec051fee27.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] add a button which gives a popup 
- [x] create a component which adds course value to the page
- [x] //server//
- [x] make a post request to add course to the page
- [ ] 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
