### ISSUE TITLE
Feature: User can color code class

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can color code class

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on a color and add color to class

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/46547520/209753888-a170ea90-b34c-49d1-a249-ec18dd9877ce.png)
![image](https://user-images.githubusercontent.com/46547520/209753997-45337baf-90fe-48fe-ac03-f6c4d9c56888.png)
![image](https://user-images.githubusercontent.com/46547520/209754042-c12451a3-754f-457c-af98-9292a3052500.png)
![image](https://user-images.githubusercontent.com/46547520/209754075-183c0080-64b5-4106-aee1-95122d6b8dae.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
